---
# --- GRUPOS ---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: cartoes-credito
  description: "Time de Cartões de Crédito"
spec:
  type: team
  owner: group:diretoria-financeira # Opcional: liga ao dono do domínio
  children: [] # Se não houver subgrupos, use os colchetes vazios
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: conta-corrente
spec:
  type: team
  children: [] 
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: pix
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: produtos-financeiros
spec:
  type: team
  children: []
