# 1. O DOMÍNIO (O topo da pirâmide de negócio)
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: Financeiro Zetra Bank
  description: Setor Financeiro da Organização
spec:
  owner: group:diretoria-financeira # Grupo que manda no setor como um todo
---
# 2. OS GRUPOS (Times de pessoas)
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: cartoes-credito
spec:
  type: team
  children: [] 
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: conta-corrente
spec:
  type: team
  children: []  
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: pix
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: diretoria-financeira
  description: "Diretoria executiva financeira"
spec:
  type: department
  children: [cartoes-credito, conta-corrente, pix, produtos-financeiros]

---
# 3. OS USUÁRIOS (Vinculados aos Grupos)
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: emanuel-silva
  description: "Responsável Técnico - Cartões de Crédito"
spec:
  memberOf: [cartoes-credito]
  profile:
    displayName: Emanuel silva
    email: emanuel.silva@engdb.com.br
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: viviane-rodrigues
  description: "Responsável Técnico - Pix"
spec:
  memberOf: [pix]
  profile:
    displayName: Viviane Rodrigues
    email: viviane.rodrigues@engdb.com.br
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: pedro-rodrigues
  description: "Responsável Técnico - Conta Corrente"
spec:
  memberOf: [conta-corrente] 
  profile:
    displayName: Pedro Rodrigues
    email: pedro.rodrigues@engdb.com.br
  

