apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: central-catalog-bootstrap
  description: "Indexador central de governança, org e arquitetura do Zetra Bank"
spec:
  targets:
    - ./domain.yaml
    - ./systems.yaml
    - ./groups.yaml
    - ./users.yaml


