# --- DOMÍNIO ---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: financeiro
spec:
  owner: group:diretoria-financeira
---
# --- GRUPOS ---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: cartoes-credito
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: conta-corrente
spec:
  type: team
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: pix
spec:
  type: team
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: produtos-financeiros
spec:
  type: team
---
# --- USUÁRIOS ---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: emanuel-silva
spec:
  memberOf: [cartoes-credito]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: pedro-rodrigues
spec:
  memberOf: [conta-corrente]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: viviane-rodrigues
spec:
  memberOf: [pix]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: edna-lemos
spec:
  memberOf: [produtos-financeiros]
